# Generated by Django 2.0.5 on 2018-05-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20180528_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='author'),
        ),
    ]
