# Generated by Django 2.0.5 on 2018-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_article_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
